version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: cpshop-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ddhai
      POSTGRES_PASSWORD: hotz2boy
      POSTGRES_DB: db_cpshop
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
