# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: next_nest_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ddhai
      POSTGRES_PASSWORD: hotz2boy
      POSTGRES_DB: db_cpshop
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: next_nest_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: